---
title: "Research"
editor: visual
---

## Job Market Paper

### The trickle-down effects of higher education affirmative action

The debate on higher education affirmative action concentrates much on the immediate beneficiaries and their prospects, disregarding that future beneficiaries might also react to the chance to pursue higher education. Effects might thus trickle-down to children who are still at school, which is a decisive stage for their future. I address this and study a higher education affirmative action law in Brazil that substantially increases public school students' chance of university admission by reserving 50% of vacancies in each major at flagship federal universities. I conceptualize students' expected effort reaction in a theoretical framework and empirically test its theoretical implications. Using administrative data from the São Paulo State School Performance Assessment System test and its rich background questionnaire, I apply a difference-in-discontinuity design and study how the affirmative action affects students' effort, performance and aspirations. Results are in line with the theoretical predictions. I find that students increase their effort at the upper end of the effort distribution. The increased effort is reflected in improved Portuguese performance. Portuguese scores increase by 2% of a standard deviation. Effects are particularly strong for disadvantaged students. Additional heterogeneity analyses suggest that increased aspirations are the driving mechanism for students' behavioral responses.

## Working Papers

### A missed opportunity? Labor demand and workforce diversity
(joint with [Anna Bindler](https://sites.google.com/site/annabindler/research), [Barbara Boelmann](https://www.barbara-boelmann.de/home), and [Lena Janys](https://sites.google.com/site/janyslena/))

<details>
<summary>Abstract</summary>
How do labor demand shocks affect workforce diversity in the absence of targeted diversity policies? A conceptual framework illustrates the potential trade-off between the demographic and quality composition of a workforce when there is a positive labor demand shock. Exploiting the German reunification as a natural experiment, we analyze the academic labor market where nearly all social sciences professors in East Germany were replaced while STEM faculty remained largely unchanged. Using administrative data and a regional difference-in-difference design, we find increased dispersion in the institutional quality of hires, indicating that the new hires came from less select departments. At the same time, female representation did not increase despite qualified women in the pipeline. Instead, East German hiring patterns converged to those in West Germany in terms of gender composition. In simulations, we investigate implied losses: Under conservative assumptions, we show that, considering the pipeline of qualified applicants, the marginal female hire’s quality is approximately half a standard deviation higher than the marginal male hire’s quality.

Working paper: Available [here](https://www.econtribute.de/RePEc/ajk/ajkdps/ECONtribute_420_2026.pdf)</details>

## Work in progress

### AI or human? Applicants’ decisions in discrimination settings
(joint with [Paula Scholz](https://paula-scholz.github.io/) and [David Stommel](https://cd.wiso.uni-koeln.de/en/team/strategic-management/david-stommel))

Draft available upon request.

Media Coverage: Queb blog post available [here](https://www.queb.org/blog/ki-im-recruiting/)

### Surfeel: Teaching Children to Verbalize Emotion
(joint with [Barbara Boelmann](https://www.barbara-boelmann.de/home), [Miguel Morin](https://www.columbia.edu/~mm3509/), and [Anna Person](https://sites.google.com/view/annaperson/home-page))

Draft available upon request.